"""
Cream LoRA Training Config Template for Kohya sd-scripts

Generates TOML configuration files for sdxl_train_network.py
Based on Realtime Lora Trainer's sdxl_config_template.py
"""

import os


def generate_training_config(
    name: str,
    image_folder: str,
    output_folder: str,
    model_path: str,
    steps: int = 1000,
    save_every_n_steps: int = 100,
    learning_rate: float = 0.0003,
    text_encoder_lr: float = 0.00003,
    lora_rank: int = 32,
    lora_alpha: int = 32,
    batch_size: int = 1,
    lr_warmup_steps: int = 100,
    network_train_unet_only: bool = False,
    cache_text_encoder_outputs: bool = False,
) -> str:
    """
    Generate a TOML config file for SDXL LoRA training with sd-scripts.

    Returns the config as a TOML string.
    """

    # Escape backslashes for TOML on Windows
    model_path_escaped = model_path.replace('\\', '/')
    image_folder_escaped = image_folder.replace('\\', '/')
    output_folder_escaped = output_folder.replace('\\', '/')

    # Text Encoder training section
    if network_train_unet_only:
        te_config = "network_train_unet_only = true"
        te_lr_line = ""
    else:
        te_config = ""
        te_lr_line = f"\ntext_encoder_lr = {text_encoder_lr:g}"

    config = f'''# SDXL LoRA Training Config
# Generated by Cream LoRA Trainer

[general]
enable_bucket = true
bucket_no_upscale = true
bucket_reso_steps = 32

[model]
pretrained_model_name_or_path = "{model_path_escaped}"

[dataset]
train_data_dir = "{image_folder_escaped}"
resolution = "1024,1024"
caption_extension = ".txt"
keep_tokens = 1

[network]
network_module = "networks.lora"
network_dim = {lora_rank}
network_alpha = {lora_alpha}
scale_weight_norms = 1
{te_config}

[optimizer]
optimizer_type = "Adafactor"
optimizer_args = ["scale_parameter=False", "relative_step=False", "warmup_init=False"]
learning_rate = {learning_rate:g}{te_lr_line}
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = {lr_warmup_steps}

[training]
output_dir = "{output_folder_escaped}"
output_name = "{name}"
save_model_as = "safetensors"
save_precision = "bf16"
max_train_steps = {steps}
save_every_n_steps = {save_every_n_steps}
train_batch_size = {batch_size}
mixed_precision = "bf16"
gradient_checkpointing = true
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = {str(cache_text_encoder_outputs).lower()}
xformers = true
fp8_base = true
full_bf16 = true
no_half_vae = true
noise_offset = 0.0357
min_snr_gamma = 5
max_data_loader_n_workers = 0
seed = 0
'''

    return config


def save_config(config_content: str, config_path: str):
    """Save config content to a TOML file."""
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(config_content)


# VRAM mode presets for SDXL
VRAM_PRESETS = {
    "Low VRAM": {
        "network_train_unet_only": True,
        "cache_text_encoder_outputs": True,
    },
    "High VRAM": {
        "network_train_unet_only": False,
        "cache_text_encoder_outputs": False,
    },
}
